### ISSUE TITLE
分片上传时 token 为 undefined，导致 401 错误

### ISSUE THREAD

**Issue by FrancisKong** [lsxiao/qiniu4js#17]
[https://github.com/lsxiao/qiniu4js/blob/master/dist/qiniu4js.es.js#L1094](https://github.com/lsxiao/qiniu4js/blob/master/dist/qiniu4js.es.js#L1094

这里使用的是 `_this.uploader.token`，导致获取的 token 为 undefined，应该是 `_this.uploader._token`

**Comment by lsxiao** [comment]
已经修复了，我测试一下就发布，这段时间工作忙着重构项目，比较忙，不好意思:)

**Comment by lsxiao** [comment]
@FrancisKong 可以了。

**Comment by FrancisKong** [comment]
效率太高了，赞～
