### ISSUE TITLE
TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by FrancisKong** [lsxiao/qiniu4js#18]
[https://github.com/lsxiao/qiniu4js/blob/master/dist/qiniu4js.es.js#L1181](https://github.com/lsxiao/qiniu4js/blob/master/dist/qiniu4js.es.js#L1181)

这里没有对`encodedKey`是否为`null`进行判断，导致在没有指定`task`的`key`值并使用分片上传时，出现 `TypeError: Cannot read property 'replace' of null`

**Comment by lsxiao** [comment]
今天下班后我会尽快修复。:)

**Comment by lsxiao** [comment]
之前pr没有仔细检查导致的，已修复了。1.0.10试试。
