### ISSUE TITLE
用uglifyjs压缩的时候报语法错误

### ISSUE THREAD

**Issue by xyDiva** [lsxiao/qiniu4js#2]
![qq 20161122143837](https://cloud.githubusercontent.com/assets/3214033/20513550/8986b1d4-b0c1-11e6-9609-f5e917103e68.png)

`SyntaxError: Unexpected token operator «*», expected punc «(»`

**Comment by lsxiao** [comment]
我刚才自己build的时候也发现了= =。
![image](https://cloud.githubusercontent.com/assets/2627625/20522444/4d329b1a-b0eb-11e6-823c-353c57ac609a.png)

**Comment by lsxiao** [comment]
@xyDiva 试试`npm install qiniu4js@1.0.2 -save--dev` 发现原来是typescript编译的代码的问题，更新了typescript后再build出来的代码没问题了。
