### ISSUE TITLE
多图片上传报错

### ISSUE THREAD

**Issue by djjeng77** [lsxiao/qiniu4js#21]
添加3个图片 2个2M多,一个6M , 不使用分片上传,上传成功的回调函数里面task.file一直第一个图片,然后就卡死,使用分片上传,直接提示分片上传失败.

**Comment by lsxiao** [comment]
之前pr没有仔细检查导致的，getToken异步执行，导致UploadPattern的upload方法多次调用，后一个task会覆盖前一个Task。导致只能上传一张，已经修复了。1.0.10试试。
