### ISSUE TITLE
上传非图片的文件好像不可以？还是要配置什么

### ISSUE THREAD

**Issue by cmideal** [lsxiao/qiniu4js#22]
如题不知道，上传是否要配置什么？

**Comment by lsxiao** [comment]
有错误日志吗

**Comment by cmideal** [comment]
找到原因了，看你源码，里面，你都用了blob，这样阻碍获得upptoken
this.resolveImageInfo = function (blob, s) {
            var widthRe = /\$\(imageInfo\.width\)/;
            var heightRe = /\$\(imageInfo\.height\)/;
            if (!widthRe.test(s) && !heightRe.test(s)) {
                return Promise.resolve(s);
            }
            // return new Promise(function (resolve) {
            //     var img = new Image();
            //     img.src = URL.createObjectURL(blob);
            //     img.onload = function () {
            //         s = s.replace(widthRe, img.width.toString());
            //         s = s.replace(heightRe, img.height.toString());
            //         resolve(s);
            //     };
            // });
        };

去掉下面这些，就没有任何问题了

**Comment by lsxiao** [comment]
刚才测试了，直传和分片上传非图片都没有问题。

**Comment by lsxiao** [comment]
![image](https://cloud.githubusercontent.com/assets/2627625/25139746/c584ffb8-2490-11e7-94e7-c74b6222548d.png)
