### ISSUE TITLE
能否解释一下几个saveKey参数的作用, 看不太明白

### ISSUE THREAD

**Issue by howareyouo** [lsxiao/qiniu4js#27]
试了几次还是不太明白几个`saveKey`设置的作用.
是对上传成功后返回的`key`命名吗? 
是否需要在生成`uptoken`时对这个参数做处理才能生效?

**Comment by lsxiao** [comment]
![image](https://user-images.githubusercontent.com/2627625/27525029-d836f03c-5a6c-11e7-9173-3ddbae8e726b.png)


https://developer.qiniu.com/kodo/manual/1272/form-upload
