### ISSUE TITLE
关于如何与富文本编辑器集成图片上传的功能!!

### ISSUE THREAD

**Issue by howareyouo** [lsxiao/qiniu4js#29]
那么我现在有一个富文件编辑器, 上传图片是需要服务端返回如下格式的数据:
```
{
  "success": true/false,
  "msg": "error message", # optional
  "file_path": "[real file path]"
}
```
我到底应该怎样设置我的`uploader`才能和这个编辑器集成?
我想了好久, 还是找不到办法和编辑器集成...

**Comment by lsxiao** [comment]
没明白你的意思，能描述一下上传的流程吗。

**Comment by howareyouo** [comment]
@lsxiao 因为编辑器: [Simditor](http://simditor.tower.im/docs/doc-config.html#anchor-upload)
要求自己发送文件上传请求, 还要求返回指定格式的响应, 是不是就没有办法集成了?

**Comment by lsxiao** [comment]
如果插件不能对上传流程做自定义的话，可以试试先上传到自己服务器，再从服务器上传到七牛。

**Comment by howareyouo** [comment]
[无奈]
