### ISSUE TITLE
无法获取上传成功后的文件

### ISSUE THREAD

**Issue by xyDiva** [lsxiao/qiniu4js#3]
上传成功后返回的key和hash值相同，拼写的domain+文件名得到的url无法打开，如果将blob转化获取得到base64的url是可以访问到图片的...

**Comment by lsxiao** [comment]
你去七牛看过这个key的文件是否已经上传了吗？

**Comment by lsxiao** [comment]
http://img.zhangtielan.com/Ft3nADjJcbRBfFYp66l0UlnxCLzi

**Comment by lsxiao** [comment]
http://img.zhangtielan.com/Ft3nADjJcbRBfFYp66l0UlnxCLzi

**Comment by xyDiva** [comment]
key我没有设置，只从后端获取到token；
domain也没有设置，所以也是默认的；

**Comment by lsxiao** [comment]
你能进七牛看看这个文件是否上传了没？

**Comment by xyDiva** [comment]
@lsxiao 这个要怎么查看？我用的是公用的域名。如果不成功的话它也会返回hash和key吗？

**Comment by lsxiao** [comment]
@xyDiva 不成功的话是不会返回任何东西的，只会返回错误信息，所以一定是上传成功了的。你没有七牛的账号密码吗？进入就可以看到文件了。

**Comment by lsxiao** [comment]
看看是不是开了原图保护，还是禁用了公共域名，使用了私有域名。

**Comment by xyDiva** [comment]
好。我看看。谢谢。
