### ISSUE TITLE
上传失败,返回400

### ISSUE THREAD

**Issue by gyh000** [lsxiao/qiniu4js#30]
chooseImage() {
    let uploader = new UploaderBuilder()
      .debug(true)
      .tokenFunc((setToken, task) => {
        let options = new URLSearchParams();
        this.http.get(`/qiniu/token`, options).subscribe(
          res => {
            console.log(res);
            setToken(res);
          }
        );
      })
      .saveKey(false)
      .build();
    uploader.chooseFile();
  }

这是我的上传七牛的方法,是去我自己的后台获取token,返回400,但是我用java后台直接上传七牛是成功,是什么地方遗漏了吗?

浏览器log
POST http://upload.qiniu.com/?1498801691273 400 (Bad Request)

**Comment by lsxiao** [comment]
能否http请求头和响应内容发出来一下。

**Comment by gyh000** [comment]
没有看到想要头信息
![2017-06-30 17 19 20](https://user-images.githubusercontent.com/10877907/27729471-994ec67a-5db8-11e7-8298-99f75c46f9a2.png)
我一开始以为是domain没设置,然后我用 'http://upload-z2.qiniu.com' 和自己写的最简单的表单上传功能是成功的,
但是用uploader方式还报403,我的key是通过后台设置的,前端saveKey是true,
