### ISSUE TITLE
上传图片失败

### ISSUE THREAD

**Issue by lenvonsam** [lsxiao/qiniu4js#4]
复制给的示例代码运行后，到taskProgress成功后，进行form上传，就无响应了
日志截图：
![bug1](https://cloud.githubusercontent.com/assets/10168476/20825223/a533904e-b89d-11e6-87a5-7c1352b1f47a.png)
代码截图：
![bug2](https://cloud.githubusercontent.com/assets/10168476/20825276/09059b9e-b89e-11e6-840c-e987f8c46fb1.png)
![bug3](https://cloud.githubusercontent.com/assets/10168476/20825328/4c06b626-b89e-11e6-90cb-8a71af94beab.png)

是设置不对还是步骤不对，麻烦指点一下，谢谢@lsxiao

**Comment by lsxiao** [comment]
@lenvonsam 你用的自己的域名吗？

**Comment by lenvonsam** [comment]
我就是用的1.0.6版本的，然后七牛是自己的域名，怎么就不行呢

**Comment by lsxiao** [comment]
@lenvonsam 不支持https

**Comment by lsxiao** [comment]
插件没问题，我关issue了。
