### ISSUE TITLE
android5.x 无法调起本机的图片库，需要配置什么吗

### ISSUE THREAD

**Issue by lenvonsam** [lsxiao/qiniu4js#5]
你好，我ios上已经调试正常了，是要在info.plist里面配置nsphone的key-value，而android需要配置什么吗
，现在点了完全没有反应

**Comment by lsxiao** [comment]
不需要特别的配置。

2016年12月13日 14:23，"lenvonsam" <notifications@github.com>写道：

**Comment by lenvonsam** [comment]
额，那就奇怪了，安卓调用不起来，现在。。。@lsxiao

**Comment by lsxiao** [comment]
等我后天回国之后帮你看看，现在在巴厘岛的，身边没电脑。

2016年12月14日 09:23，"lenvonsam" <notifications@github.com>写道：

**Comment by lenvonsam** [comment]
好的，谢谢你了，我试过了好几个安卓手机，都是chooseFile都是没反应的

**Comment by lsxiao** [comment]
你用chrome调试过Android的浏览器了吗？有什么错误日志没？

**Comment by simbawu610** [comment]
`value: function chooseFile() {
            this.fileInput.click();
        }`

请问 为什么IOS下 这个click事件不触发呢？
