### ISSUE TITLE
为什么typescript写的发布的包里面不生成d.ts 方便typescript 直接用。

### ISSUE THREAD

**Issue by M-Adoo** [lsxiao/qiniu4js#7]
干得漂亮，真准备自己写一个，官方的难用。

**Comment by lsxiao** [comment]
TypeScript可以直接 import .ts文件吧。

**Comment by M-Adoo** [comment]
发布的npm包里面。

**Comment by lsxiao** [comment]
@M-Adoo 哈哈，脑子短路了，dist里面没有ts文件，我今天发布一下。

**Comment by lsxiao** [comment]
1.0.8 output .d.ts

**Comment by baoziv587** [comment]
1.0.10 的release里并没有找到 d.ts 啊。
![image](https://cloud.githubusercontent.com/assets/7347513/26147845/5a45df08-3b27-11e7-87df-5dcc5d7c578e.png)

把typings提交到[TS的官方仓库]把(https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by lsxiao** [comment]
1.0.11
